export const RECEIVE_ANNOTATIONS = 'RECEIVE_ANNOTATIONS';
export const RECEIVE_GROUP = 'RECEIVE_GROUP';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_AUTH_STATUS = 'UPDATE_AUTH_STATUS';
export const FETCH_USER = 'FETCH_USER';
