// articles
export const LOAD_ARTICLES_REQUEST = 'LOAD_ARTICLES_REQUEST';
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';
export const LOAD_ARTICLES_FAILURE = 'LOAD_ARTICLES_FAILURE';

// annotations
export const LOAD_ANNOTATIONS_REQUEST = 'LOAD_ANNOTATIONS_REQUEST';
export const LOAD_ANNOTATIONS_SUCCESS = 'LOAD_ANNOTATIONS_SUCCESS';
export const LOAD_ANNOTATIONS_FAILURE = 'LOAD_ANNOTATIONS_FAILURE';
export const LOAD_DISCUSSION_SUCCESS = 'LOAD_DISCUSSION_SUCCESS';
export const LOAD_DISCUSSION_FAILURE = 'LOAD_DISCUSSION_FAILURE';
export const RECEIVE_ANNOTATIONS = 'RECEIVE_ANNOTATIONS';
export const RECEIVE_REPLY = 'RECEIVE_REPLY';

// groups
export const RECEIVE_GROUP = 'RECEIVE_GROUP';

// user
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_AUTH_STATUS = 'UPDATE_AUTH_STATUS';
export const FETCH_USER = 'FETCH_USER';
