/* eslint-disable max-len */

const fakeDB = [
  {
    id: 'abcd190d',
    slug: 'struggle-is-real',
    title: 'Officials Struggling To Condense Trump’s Intelligence Briefing Down To One Word',
    domain: 'theonion.com (satire)',
    subtitle: 'The president tends to grow frustrated if crucial intelligence is not delivered within the first seven letters or so. We recently gave him a briefing that consisted only of the term ‘nuclear proliferation,’ but he clearly became distracted by the end of the first word, so we shortened it to simply read bomb',
    annotationContent: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque mattis mollis elit, sit amet facilisis erat. Mauris condimentum ex vel neque cursus, eu bibendum velit eleifend. Praesent molestie odio eget interdum ultricies. Nullam vitae dictum sapien, condimentum ultrices elit.',
    image: 'http://i.onionstatic.com/onion/5597/9/16x9/1600.jpg',
    name: 'merwin',
    points: 16,
    timeSince: '2 hours',
    numUsers: 3,
    numAnnotations: 6,
    numReplies: 4,
    currentVotes: 43,
  },
  {
    id: 'xys190a',
    slug: 'new-freedom',
    title: 'Immigration Agents Discover New Freedom to Deport Under Trump',
    domain: 'nytimes.com',
    subtitle: 'perhaps the biggest change was the erasing of the Obama administration’s hierarchy of priorities, which forced agents to concentrate on deporting gang members and other violent and serious criminals, and mostly leave everyone else alone',
    annotationContent: 'Prioritization is particularly important when we have limited resources, even more so when the matters are pressing (violent crime). I can foresee one unforseen consequence being less attention to violent criminals in favor of deporting lower hanging fruit. While Trump says he wants to hire a ludricous number of immigration officers, hiring and training them will likely be a long process.',
    image: 'https://static01.nyt.com/images/2017/02/26/us/26ICEMASHUP/26ICEMASHUP-superJumbo.jpg',
    name: 'byrne',
    points: 22,
    timeSince: '21 hours',
    numUsers: 3,
    numAnnotations: 6,
    numReplies: 4,
    currentVotes: 5,
  },
  {
    id: '128sd043hd',
    slug: 'struggle-is-real-again',
    title: 'Officials Struggling To Condense Trump’s Intelligence Briefing Down To One Word',
    domain: 'theonion.com (satire)',
    subtitle: 'The president tends to grow frustrated if crucial intelligence is not delivered within the first seven letters or so. We recently gave him a briefing that consisted only of the term ‘nuclear proliferation,’ but he clearly became distracted by the end of the first word, so we shortened it to simply read bomb',
    annotationContent: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque mattis mollis elit, sit amet facilisis erat. Mauris condimentum ex vel neque cursus, eu bibendum velit eleifend. Praesent molestie odio eget interdum ultricies. Nullam vitae dictum sapien, condimentum ultrices elit.',
    image: 'http://i.onionstatic.com/onion/5597/9/16x9/1600.jpg',
    name: 'merwin',
    points: 6,
    timeSince: '2 hours',
    numUsers: 3,
    numAnnotations: 6,
    numReplies: 4,
    currentVotes: 5,
  },
  {
    id: 'abcd190e',
    slug: 'san-juan-is-not-lame',
    title: 'Its all made up!',
    domain: 'sanjuan.org',
    subtitle: 'San Juan is a friendly cucumber',
    annotationContent: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque mattis mollis elit, sit amet facilisis erat. Mauris condimentum ex vel neque cursus, eu bibendum velit eleifend. Praesent molestie odio eget interdum ultricies. Nullam vitae dictum sapien, condimentum ultrices elit.',
    image: 'https://ih1.redbubble.net/image.119457339.8676/flat,1000x1000,075,f.u6.jpg',
    name: 'lcow',
    points: 44,
    timeSince: '1 hour',
    numUsers: 3,
    numAnnotations: 6,
    numReplies: 4,
    currentVotes: 5,
  },
];

export default fakeDB;
